apiVersion: 1
kind: Deployment
metadata:
  name: mongoDB_deployment
  labels:
    app: mongoDB
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mongoDB
  template:
    metadata:
      labels:
        app: mongoDB
    spec: 
      containers:
      - name: mongoDB
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb_secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb_secret
              key: mongo-root-password
---
apiVersion: 1
kind: Service
metadata: 
  name: mongoDB_service
spec:
  selector:
    app: mongoDB
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017